import{a as L,i as f,S as E}from"./assets/vendor-5f0e12e0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const w="2573416-853329f61ff5a3b6beba25569",v="https://pixabay.com/api/",S=L.create({baseURL:v,timeout:1e4});async function y({searchQuery:t,page:r}){return(await S.get("/",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})).data}const d={position:"topRight",messageColor:"#fff"},O=document.querySelector(".search-form"),i=document.querySelector(".gallery"),m=document.querySelector(".loader");let l="",u=0,c=1;O.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.searchQuery.value.toLowerCase().trim();if(r){l=r,c=1,t.target.elements.searchQuery.value="",i.innerHTML="",m.classList.remove("hide");try{const{hits:o,total:n}=await y({searchQuery:l,page:c});o.length||f.show({...d,message:"We're sorry, but images to your request didn't find.",color:"#ef5350"}),u=n,h(g(o),!0),f.show({...d,message:`Hooray! We found ${u} images.`,color:"#7dc67d"})}catch(o){console.error("Error!!!!",o)}finally{m.classList.add("hide")}}});function h(t,r=!1){i.lastElementChild&&p.unobserve(i.lastElementChild),r?i.innerHTML=t:i.insertAdjacentHTML("beforeend",t),p.observe(i.lastElementChild),new E(".gallery a",{captionSelector:"img",captionsData:"alt",captionDelay:250})}function g(t){return t.map(({webformatURL:r,largeImageURL:o,tags:n,likes:e,views:s,comments:a,downloads:b})=>`
        <li class="photo-card">
          <a href="${o}">
            <img src="${r}" alt="${n}" loading="lazy" height="220" />
            </a>
            <div class="info">
              <p class="info-item"><b>Likes</b> ${e}</p>
              <p class="info-item"><b>Views</b> ${s}</p>
              <p class="info-item"><b>Comments</b> ${a}</p>
              <p class="info-item"><b>Downloads</b> ${b}</p>
            </div>
        </li>
  `).join("")}async function P(){c+=1;const{hits:t}=await y({searchQuery:l,page:c});return t}const p=new IntersectionObserver(async t=>{const r=i.childElementCount;if(!(t[0].intersectionRatio<=0||r===u))try{const o=await P();h(g(o))}catch(o){console.error("observer error",o)}});
//# sourceMappingURL=commonHelpers.js.map
