import{a as E,S as v,i as d}from"./assets/vendor-5f0e12e0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const a of s.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerpolicy&&(s.referrerPolicy=e.referrerpolicy),e.crossorigin==="use-credentials"?s.credentials="include":e.crossorigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=o(e);fetch(e.href,s)}})();const w="2573416-853329f61ff5a3b6beba25569",S="https://pixabay.com/api/",O=E.create({baseURL:S,timeout:1e4});async function h({searchQuery:t,page:r}){return(await O.get("/",{params:{key:w,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:40}})).data}const f={position:"topRight",messageColor:"#fff"},P=document.querySelector(".search-form"),n=document.querySelector(".gallery"),m=document.querySelector(".loader"),y=document.querySelector(".end_text"),C=new v(".gallery a",{captionSelector:"img",captionsData:"alt",captionDelay:250});let u="",c=0,l=1;P.addEventListener("submit",async t=>{t.preventDefault();const r=t.target.elements.searchQuery.value.toLowerCase().trim();if(r){u=r,l=1,t.target.elements.searchQuery.value="",n.innerHTML="",m.classList.remove("hide"),y.classList.add("hide");try{const{hits:o,totalHits:i}=await h({searchQuery:u,page:l});if(!o.length){d.show({...f,message:"We're sorry, but images to your request didn't find.",color:"#ef5350"});return}c=i,g(b(o),!0),d.show({...f,message:`Hooray! We found ${c} totalHits images.`,color:"#7dc67d"})}catch(o){console.error("Error!!!!",o)}finally{m.classList.add("hide")}}});function g(t,r=!1){n.lastElementChild&&p.unobserve(n.lastElementChild),r?n.innerHTML=t:n.insertAdjacentHTML("beforeend",t),p.observe(n.lastElementChild),C.refresh(),n.childElementCount===c&&y.classList.remove("hide")}function b(t){return t.map(({webformatURL:r,largeImageURL:o,tags:i,likes:e,views:s,comments:a,downloads:L})=>`
        <li class="photo-card">
          <a href="${o}">
            <img src="${r}" alt="${i}" loading="lazy" height="220" />
            </a>
            <div class="info">
              <p class="info-item"><b>Likes</b> <span>${e}</<span></p>
              <p class="info-item"><b>Views</b> <span>${s}</<span></p>
              <p class="info-item"><b>Comments</b> <span>${a}</<span></p>
              <p class="info-item"><b>Downloads</b> <span>${L}</<span></p>
            </div>
        </li>
  `).join("")}async function T(){l+=1;const{hits:t}=await h({searchQuery:u,page:l});return t}const p=new IntersectionObserver(async t=>{const r=n.childElementCount;if(!(t[0].intersectionRatio<=0||r===c))try{const o=await T();g(b(o))}catch(o){console.error("observer error",o)}});
//# sourceMappingURL=commonHelpers.js.map
